name: query_stack
description: Powerful, yet simple, asynchronous state management for Flutter
version: 1.0.0-dev.11
homepage: https://github.com/JCKodel/query_stack

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.0
